// <auto-generated />
using System;
using LVT.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LVT.Data.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LVT.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LVT.Models.Entities.VehicleAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlarmCameraId")
                        .HasColumnName("alarm_cam_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmGenerationTime")
                        .HasColumnName("alarm_generation_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmLocation")
                        .HasColumnName("alarm_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChassisNo")
                        .HasColumnName("chassis_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnName("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNo")
                        .HasColumnName("engine_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirNO")
                        .HasColumnName("fir_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirPoliceStation")
                        .HasColumnName("fir_police_station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnName("image_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigatorName")
                        .HasColumnName("investigator_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnName("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnName("owner_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnName("registration_no")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("ReportedOn")
                        .HasColumnName("reported_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("vehicle_alarms");
                });
#pragma warning restore 612, 618
        }
    }
}
